
project:
  type: website

website:
  title: "T1 Strategy"
  navbar:
    background: black
    left:
      - href: index.qmd
        text: Home
      - href: investment/index.qmd
        text: Investment
      - href: hobbies/index.qmd
        text: Hobbies
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: none
    css: styles.css
    toc: true
